[project]
name = 'guideX_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.daily_update_limits]
path = 'contracts/daily_update_limits.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_availability]
path = 'contracts/data_availability.clar'
clarity_version = 2
epoch = 2.5

[contracts.multiple_voting_rounds]
path = 'contracts/multiple_voting_rounds.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
